// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jchnjeihrutgmfjwnfyo.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImpjaG5qZWlocnV0Z21manduZnlvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDM1OTk2ODIsImV4cCI6MjA1OTE3NTY4Mn0.Mkn0XWEwElTiFWNLjm58PfSoj6QT-zUMisaCQxqtqHs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    persistSession: true,
    autoRefreshToken: true,
    detectSessionInUrl: true,
    storage: window.localStorage,
    flowType: 'pkce'
  },
  global: {
    headers: {
      'x-application-name': 'meta-construtor'
    }
  },
  db: {
    schema: 'public'
  },
  realtime: {
    params: {
      eventsPerSecond: 10
    }
  },
  network: {
    retry: {
      count: 3,
      delay: 1000,
      maxDelay: 5000
    },
    timeout: 30000
  }
});